##ocultar stacktrace
server:
  error:
    include-stacktrace: never
##config database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
#exibir log do comando hibernate
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG